### PR TITLE
Dennis Tolle Solution for Lesson 01

### PR DESCRIPTION
**Pull request by TolleDennis**

### CODE REVIEW

**Comment by TolleDennis** [comment]
Requested

**Comment by quangnh-2761** [comment]
@TolleDennis Overall you are doing quite well, just some small errors that I think you can easily fix. You can submit again after completing and I will help you to check.
Assignment 7: The first requirement asked you to make the `Employee` class call `__init__` function of base class, which in this case is class `Person`. More particular, you have to pass attributes to arguments of `Person` class init function. Try to figure out how to call that inside `Employee` init function
Assignment 9: For the two latter case, you have to compute the exact values of solutions, instead of just printing the number of solutions. You did calculate the discriminant of quadratic equation, it is straightforward to obtain its solutions then.

**Comment by TolleDennis** [comment]
answer to 9. Is this the correct way as per the instructions?

**Comment by quangnh-2761** [comment]
I've checked your last commit, you did it right now. Good job!

**Comment by TolleDennis** [comment]
Thanks a lot for the guide and help

**Comment by TolleDennis** [comment]
Solution for Lesson 2

**Pull request closed without merging**
