### PR TITLE
[Dennis Tolle] Solution for Lesson 3

### PR DESCRIPTION
**Pull request by TolleDennis**
Logistic Regression

### CODE REVIEW

**Comment by TolleDennis** [comment]
Logistic Regression

**Comment by TolleDennis** [comment]
Logistic Regression

**Comment by TolleDennis** [comment]
Logistic Regression

**Comment by hieubhm-1071** [comment]
@TolleDennis 
Nice job on the assignment, you got most of them correct aside from the accuracy function.
Y_predict and Y are 2 arrays of the same length so the correct way to loop through them is using range (len(Y)).

**Pull request closed without merging**
